name: Yggdrasil deployment

on:
  push:
    branches: [ "prod", "phoenix" ]

permissions:
  pull-requests: write
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:jumpscare-ci
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn install
      - name: ssh-keyscan 10.1.3.1
        run: |
          mkdir -p ~/.ssh/
          echo "$KIRITO_SSH_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          ssh-add
          ssh-keyscan -H 10.1.3.1 > ~/.ssh/known_hosts
      - run: npx pm2 deploy yggdrasil.config.cjs phoenix
        if: github.ref_name == 'phoenix'
      - run: npx pm2 deploy yggdrasil.config.cjs production
        if: github.ref_name == 'prod'
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Changes deployed to server
            Environment ${{ github.ref_name }}